import java.util.Random;
import javax.swing.JOptionPane;

public class Menu_Petiscos extends javax.swing.JFrame {

    public Menu_Petiscos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoRoleta = new javax.swing.JButton();
        botaoBlackJack = new javax.swing.JButton();
        botaoDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cassino Floquinho");

        botaoRoleta.setText("Roleta - Petisco Carne");
        botaoRoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRoletaActionPerformed(evt);
            }
        });

        botaoBlackJack.setText("BlackJack - Petisco Frango");
        botaoBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBlackJackActionPerformed(evt);
            }
        });

        botaoDados.setText("Dados - Petisco Cenoura");
        botaoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Petiscos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(botaoRoleta)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoBlackJack)
                                .addGap(18, 18, 18)
                                .addComponent(botaoDados))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRoleta)
                    .addComponent(botaoBlackJack)
                    .addComponent(botaoDados))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRoletaActionPerformed
        
        int num_armazenado = Integer.parseInt (JOptionPane.showInputDialog (null, "Olá! Qual número você deseja apostar?"));
        
        Random n = new Random();
        
        int numero = n.nextInt(37);
        int i = 0;
        
        do{
        if (num_armazenado == numero){
            JOptionPane.showMessageDialog(null, "Parabéns! Você ganhou! " + numero); i = 1;break;}
        else{num_armazenado = Integer.parseInt(JOptionPane.showInputDialog(null,"Tente novamente!"));
        }
        }while (i == 0);
        
    }//GEN-LAST:event_botaoRoletaActionPerformed

    private void botaoBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBlackJackActionPerformed
        
        Random num_mesa  = new Random();
        
        int num1, num2, num3;
        
        num1 = num_mesa.nextInt(10);
        num2 = num_mesa.nextInt(10);
        num3 = num_mesa.nextInt(10);
        
        int num = num1 + num2 + num3;
        
        Random n = new Random();
        
        int numero1, numero2, numero3;
       
        numero1 = n.nextInt(10);
        numero2 = n.nextInt(10);
        numero3 = n.nextInt(10);
        
        JOptionPane.showMessageDialog(null, "Seu primeiro número foi: " + numero1 + ".");
        JOptionPane.showMessageDialog(null, "Seu segundo número foi: " + numero2 + ".");
        JOptionPane.showMessageDialog(null, "Seu terceiro número foi: " + numero3 + ".");
       
        int soma;
        
        soma = numero1 + numero2 + numero3;
        
        JOptionPane.showMessageDialog(null, "Sua soma foi: " + soma + ".");
        JOptionPane.showMessageDialog(null, "O número da mesa foi: " + num + ".");
        
        if (num > 21){
            JOptionPane.showMessageDialog(null,"Parabéns! Você ganhou porque a mesa ultrapassou o número 21. O número foi: " + num);
        }
        
        if(num > soma){
            JOptionPane.showMessageDialog(null,"Você perdeu! Pois o número da mesa é maior que o seu. Tente novamente! Sua soma foi: " + soma + ".");
        }
        
        if(soma > num){
            JOptionPane.showMessageDialog(null,"Você ganhou! Sua soma foi maior que o número da mesa.");
        }
        
        if(soma > 21){
            JOptionPane.showMessageDialog(null,"Você perdeu. Sua soma ultrapassou o número 21. Tente novamente!");
        }
        
    }//GEN-LAST:event_botaoBlackJackActionPerformed

    private void botaoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDadosActionPerformed
       
       int num_soma;
       int num_armazenado = Integer.parseInt (JOptionPane.showInputDialog(null,"Quantos petiscos você deseja apostar?"));
       
       Random n = new Random();
        
       int dado1 = n.nextInt(6);
       int dado2 = n.nextInt(6);
       
       JOptionPane.showMessageDialog (null,"Seu 1º dado teve o valor de: " + dado1 + ".");
       JOptionPane.showMessageDialog (null,"Seu 2º dado teve o valor de: " + dado2 + ".");
       
       int soma = dado1 + dado2;
       
       if(soma > 7){
           JOptionPane.showMessageDialog(null, "Você ganhou! " + soma + ".");
           num_soma = num_armazenado * 2;
           JOptionPane.showMessageDialog (null,"Agora seus petiscos são: " + num_soma + ".");
       }
       
       if(soma < 7){
           JOptionPane.showMessageDialog(null,"Você perdeu! Tente novamente! Sua soma foi: " + soma + ".");
       }
    }//GEN-LAST:event_botaoDadosActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Petiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Petiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Petiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Petiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Petiscos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBlackJack;
    private javax.swing.JButton botaoDados;
    private javax.swing.JButton botaoRoleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
